name: Storm Stewards
brand_name: Storm Stewards
button_adopt: Claim!
update_report: "%{title} import (%{deleted_adopted_count} claimed %{things} removed, %{created_count} %{things} added, %{deleted_unadopted_count} unclaimed %{things} removed)" #needs to be in quotes, can't have % as first character in value
default_tagline: What does it mean to be a Storm Steward? 
notices_adopted: You just claimed a drain 
titles_adopt: Claim this drain
titles_adopted:  This drain has been claimed
titles_adopted_tagline: "{count} drains claimed in %{city}"
titles_main: Storm Stewards %{city}
sign_in: Sign in to be a Storm Steward
thank_you: Thank you for being a Storm Steward for this drain!
title_email_text: I just claimed one of %{city}'s storm drains and pledged to help keep it clear of leaves and debris. You, too, can be a Storm Steward and help the City avoid flooding at %{root_url}."
title_tweet_text: Flooded streets aren't fun. I claimed my own %{city} storm drain at %{root_url}. Claim and name yours.
site_description: You can claim one of %{city}'s storm drains and pledge to help keep it clear of leaves and debris this rainy season. Lend a hand and help the City avoid flooding.
gis_icon_adopted: Claimed
gis_icon_in_need: In Need of Care
imperative: claim
past_tense_verb: claimed
gerund: claiming
details_partial_name: sidebar/details_storm_stewards