version: "3"
name: adopt-a-drain
services:
  db:
    image: postgis/postgis:14-3.2-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  web:
    # TODO: Do I need to precompile? heroku seems to do it automatically https://devcenter.heroku.com/articles/rails-asset-pipeline
    build: .
    command: bundle exec rails s -p ${PORT} -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT
      - DB_HOST
      - DB_PASSWORD
      - DB_USER
      - GOOGLE_MAPS_JAVASCRIPT_API_KEY
      - GOOGLE_GEOCODER_API_KEY
      - GOOGLE_MAPS_KEY
      - SECRET_KEY_BASE
      - MAILSERVER_HOST
      - MAILSERVER_DOMAIN
      - MAILSERVER_USERNAME
      - MAILSERVER_PASSWORD

    depends_on:
      - db

volumes:
  postgres: {}
