version: '2'
services:
  db:
    image: postgres:14.2-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  web:
    build: .
    command: bundle exec rails s -p ${PORT:-3000} -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      PORT: ${PORT:-3000}
    depends_on:
      - db

volumes:
  postgres: {}