city:
  state: Massachusetts
  tos_partial_name: sidebar/tos_adopt_a_drain
  contact_email: contact@mysticriver.org
site:
  brand: adopt-a-drain
  video: https://www.youtube.com/embed/269AeYt_S9s
org:
  email: contact@mysticriver.org
  name: Mystic River Watershed Association
  logo: logos/mrwa-logo.png
  url: https://mysticriver.org
  phone: 781-393-2137
