city:
  state: Massachusetts
site:
  brand: adopt-a-drain
org:
  email: contact@mysticriver.org
  name: Mystic River Watershed Association
  logo: logos/mrwa-logo.png
  url: https://mysticriver.org
  phone: 781-393-2137
