city:
  name: Everett
  type: City
  center:
    lat: "42.4083274"
    lng: "-71.0564758"
  title: City of Everett
  runoff_destination: the Mystic River or Lakes
  trash_page_label: Everett's recycling page
  trash_page_url: https://cityofeverett.com/city-hall/departments/public-works/recycling/
  report_issues: by contacting the Mayor's office at 617-394-2270
  logo: logos/everett-city.png
  url: https://cityofeverett.com/
  facebook: https://www.facebook.com/cityofeverettma
  instagram: https://www.instagram.com/cityofeverettma/
  twitter: https://twitter.com/cityofeverettma?lang=en
  linkedin: https://www.linkedin.com/company/everettma/
site:
  domains: [localhost, everett.localhost, everett.mysticdrains.org]
  main_url: https://everett.mysticdrains.org/
  logo: logos/adopt-a-drain-everett.png
data:
  file: Everett_Drain_Catch_Basin_WGS84_20220421.csv
  columns:
    id: CB_ID
    lat: Latitude
    lng: Longtitude
    name: [StreetName, CB_ID]
