city:
  name: Medford
  type: City
  center:
    lat: "42.4184296"
    lng: "-71.1061639"
  title: City of Medford
  state: Massachusetts
  runoff_destination: the Mystic River or Lakes
  trash_page_label: Medford’s trash and recycling page
  trash_page_url: https://www.medfordma.org/departments/department-of-public-works/
  report_issues: via <a target="_blank" href=" https://www.medfordma.org/mayor/online-request-for-city-service"> SeeClickFix </a> or contact Medford Department of Public Works at 781-393-2417
  logo: logos/medford-city.png
  url: https://www.medfordma.org/
  facebook: https://www.facebook.com/GoGreenMedford
  instagram: https://www.instagram.com/gogreenmedford/?hl=en
  twitter: https://twitter.com/GoGreenMedford
  linkedin: https://www.linkedin.com/company/city-of-medford-medford-ma-02155/
site:
  domains: [medford.localhost, medford.mysticdrains.org]
  main_url: https://medford.mysticdrains.org/
  logo: logos/adopt-a-drain-medford.png
data:
  file: medford_drains.csv
  columns:
    id: watershed
    lat: lat
    lng: lon
    name: [type]
