map_center:
  lat: '42.4184296'
  lng: '-71.1061639'
city:
  name: Medford
  type: City
app_url: https://adopt-a-drain-medford-mass.herokuapp.com/
details:
  destination: the Mystic River or Lakes
  trash_page_label: Medford’s trash and recycling page
  trash_page_url: https://www.medfordma.org/departments/department-of-public-works/
  contact_email: enviro@medford-ma.gov
  contact_name: the Office of Energy & Environment
  report_issues: via <a target="_blank" href=" https://www.medfordma.org/mayor/online-request-for-city-service"> SeeClickFix </a> or contact Medford Department of Public Works at 781-393-2417