map_center:
  lat: "42.4184296"
  lng: "-71.1061639"
city:
  name: Medford
  type: City
  state: Massachusetts
domains: [medford.localhost, medford.mysticdrains.org]
main_url: https://medford.mysticdrains.org/
details:
  destination: the Mystic River or Lakes
  trash_page_label: Medford’s trash and recycling page
  trash_page_url: https://www.medfordma.org/departments/department-of-public-works/
  contact_email: enviro@medford-ma.gov
  contact_name: the Office of Energy & Environment
  report_issues: via <a target="_blank" href=" https://www.medfordma.org/mayor/online-request-for-city-service"> SeeClickFix </a> or contact Medford Department of Public Works at 781-393-2417
sponsors:
  dev: Coronado Consulting
  dev_logo: logos/coronado.png
  dev_url: mailto:j.korenstein@gamedaymatchup.net?subject=Inquiry about technology behind Adopt-A-Drain
  org: Medford Public Works
  org_logo: logos/medford-org.png
  org_url: https://medfordenergy.org/gogreen/
  city: City of Medford
  city_logo: logos/medford-city.png
  city_url: https://www.medfordma.org/
socials:
  site_url: https://medfordenergy.org/gogreen/
  site_label: gogreenmedford.org
  facebook: https://www.facebook.com/GoGreenMedford
  instagram: https://www.instagram.com/gogreenmedford/?hl=en
  twitter: https://twitter.com/GoGreenMedford
  linkedin: https://www.linkedin.com/company/city-of-medford-medford-ma-02155/
  email: enviro@medford-ma.gov
  phone: 781-393-2137
adopt_a_drain_logo: logos/adopt-a-drain-medford.png
titles:
  main: Adopt-a-Drain Medford
data:
  file: medford_drains.csv
  columns:
    id: watershed
    lat: lat
    lng: lon
    name: [type]
