map_center:
  lat: "37.774929"
  lng: "-122.419416"
city:
  name: <%= CityHelper.p("city.name") %>
  type: <%= CityHelper.p("city.type") %>
domains: [placeholder.localhost]
main_url: https://placeholder.mysticdrains.org/
details:
  destination: <%= CityHelper.p("details.destination") %>
  trash_page_label: <%= CityHelper.p("details.trash_page_label") %>
  trash_page_url: <%= CityHelper.p("details.trash_page_url") %>
  contact_email: <%= CityHelper.p("details.contact_email") %>
  contact_name: <%= CityHelper.p("details.contact_name") %>
  report_issues: <%= CityHelper.p("details.report_issues") %>
sponsors:
  dev: Coronado Consulting
  dev_logo: logos/coronado.png
  dev_url: mailto:j.korenstein@gamedaymatchup.net?subject=Inquiry about technology behind Adopt-A-Drain
  org: Mystic River Watershed Association
  org_logo: logos/mrwa-logo.png
  org_url: https://example.com
  city: Placeholder city
  city_logo: logos/placeholder-logo.png
  city_url: https://example.com
adopt_a_drain_logo: logos/placeholder-logo.png
titles:
  main: Adopt-a-Drain Placeholder
socials:
  site_url: https://medfordenergy.org/gogreen/
  site_label: gogreenmedford.org
  facebook: https://www.facebook.com/GoGreenMedford
  instagram: https://www.instagram.com/gogreenmedford/?hl=en
  twitter: https://twitter.com/GoGreenMedford
  linkedin: https://www.linkedin.com/company/city-of-medford-medford-ma-02155/
  email: enviro@medford-ma.gov
  phone: 781-393-2137
