city:
  name: Reading
  type: Town
  center:
    lat: "42.5335964"
    lng: "-71.1386262"
  title: Town of Reading
  runoff_destination: the Mystic River or Lakes
  trash_page_label: Reading's rubbish and recycling page
  trash_page_url: https://www.readingma.gov/248/Rubbish-Recycling
  report_issues: via <a target="_blank" href="https://seeclickfix.com/reading">SeeClickFix</a>
  logo: logos/reading-city.png
  url: https://www.readingma.gov/
  facebook: https://www.facebook.com/ReadingGov
  twitter: https://twitter.com/TownofReadingMA
  linkedin: https://www.linkedin.com/company/town-of-reading-ma/
site:
  domains: [localhost, reading.localhost, reading.mysticdrains.org]
  main_url: https://reading.mysticdrains.org/
  logo: logos/adopt-a-drain-reading.png
data:
  file: Reading_catchbasins_WGS84_20220623.csv
  columns:
    id: SYSTEMID
    lat: Latitude
    lng: Longitude
    name: [LOCDESC]
