city:
  name: Somerville
  type: City
  center:
    lat: "42.38838449396033"
    lng: "-71.10095828878448"
  title: City of Somerville
  runoff_destination: the Mystic and Charles Rivers
  trash_page_label: Somerville's trash and recycling page
  trash_page_url: https://www.somervillema.gov/departments/dpw-sanitation/somerville-trash-recycling-information
  report_issues: <a target="_blank" href="https://www.somervillema.gov/departments/constituent-services/311-service-center">online</a> or by calling 311
  logo: logos/somerville-city.png
  url: https://www.somervillema.gov/
  facebook: http://www.facebook.com/SomervilleCity
  instagram: http://instagram.com/somervillecity
  twitter: https://twitter.com/Somervillecity
  linkedin: https://www.linkedin.com/company/city-of-somerville/
site:
  domains: [somerville.localhost, somerville.mysticdrains.org]
  main_url: https://somerville.mysticdrains.org/
  logo: logos/adopt-a-drain-somerville.png
data:
  file: somerville-catch-basins-2023-05-07.csv
  columns:
    lat: "Y"
    lng: "X"
